Repository lern-fair-file-sharing/backend, pull requests merged in 2024-06, with the labels that each got.

#10 fix trusted domain and automatic admin
  docker-compose.yml
  secrets/nextcloud_admin_password.txt
  secrets/nextcloud_admin_user.txt
  secrets/postgres_db.txt
  secrets/postgres_password.txt
  secrets/postgres_user.txt
Labels: bug

#12 Adds redis container for caching
  docker-compose.yml
Labels: enhancement

#13 Allow "10*" prefixed domains as trusted
  docker-compose.yml
Labels: bug, infrastructure
